### ISSUE TITLE
Danke !!!

### ISSUE THREAD

**Issue by Farmer200** [Mmtrx/FS22_ChaffMission#1]
Da hast du wieder ein Ding rausgekloppt echt Super !!!

**Comment by Maestro-Ralf** [comment]
@Farmer200  Der Autor hat den Fehler bereits behoben Download und versuche es bei mir funktioniert alles.

**Comment by Farmer200** [comment]
Nein du hast das falsch verstanden ich hatte kein Problem ich bin nur begeistert von der Spielerweiterung.

**Comment by Gordon-Dry** [comment]
Dann würde ich diese "issue" nach der Danksagung sofort schließen, da das "Problem" dann ja behoben ist.

**Comment by Farmer200** [comment]
Sorry für die Irritation. Ich bin immer noch schwer begeistert.

**Comment by Farmer200** [comment]
Sorry ich bekomm es nicht geschlossen. Ich weiß nicht wie.
