### ISSUE TITLE
Auf "sinnvolle" Abladestellen begrenzen

### ISSUE THREAD

**Issue by TobiHH78** [Mmtrx/FS22_ChaffMission#11]
Gibt es eine Möglichkeit die möglichen Ablieferstellen zu begrenzen? Anscheinend trägt sich das in jede Verkaufsstation ein,
Häckselgut aber beim Restaurant oder der Schreinerei abzuliefern ergibt nicht viel Sinn.
Kann man das irgendwie nur in bestimmte Verkaufsstellen eintragen bzw. bestimmte Verkaufsstationen davon ausnehmen?

**Comment by VidhosticeSDK** [comment]
The script also finds STRAWBERRY as STRAW
by adding a space to the end of the string we can test the crop with a space at the end.

string.find(fillTypeNames.." ", "WHEAT ") or string.find(fillTypeNames.." ", "STRAW ")

**Comment by VidhosticeSDK** [comment]
Better look for fillType - GRASS_WINDROW on our map.
elseif string.find(" "..fillTypeNames.." ", " GRASS_WINDROW ") then 

And you can also add a space at the beginning if I were to search for example GRASS_WINDROW instead of DRYGRASS_WINDROW

**Comment by Mmtrx** [comment]
Ok, good idea. Intention is to add chaff only to those sellpoints that also take straw or hay. 

Will update that soon. 😀

**Comment by Mmtrx** [comment]
Please test [this](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.2.0). Version still writes debug messages to the log.

**Comment by VidhosticeSDK** [comment]
function isTargetFilltype(typeNames)
	-- return true if typeNames contain straw or hay
	local txt = " "..typeNames.." "
	if string.find(txt, " GRASS_WINDROW ") or string.find(txt, " STRAW ") then 
		return true 
	end
	return false
end

I would add an empty character before the tested string
(elimination of DRYGRASS_WINDROW)
DRYGRASS_WINDROW is taken by a heating plant (incinerator) - and that's not a good redemption point 😃


🤠👍

**Comment by Mmtrx** [comment]
Ok. But I did that on purpose - thinking that a sellpoint taking straw, grass, or hay should also take chaff. 
AND hay even burns better than grass 😉.
