### ISSUE TITLE
Landhandel Ballen auf der Landersum Map nimmt weder GPS noch Häckselgut an

### ISSUE THREAD

**Issue by Justice-Molton** [Mmtrx/FS22_ChaffMission#15]
Hallo,
erst einmal vielen Dank für diesen Mod. So etwas war lange überfällig.
Ich spiele auf der Landersum Map. Das Abliefern am Landhandel für Ballen funktioniert nicht. Es gibt einen weiteren Ballenhandel, bei dem es klappt. Leider weiß ich nicht genau, was ich anpassen muss, damit es auch beim anderen funktioniert.

**Comment by Mmtrx** [comment]
Hm,
hab grad mal in die `landHandelBallen.xml` im Landersum mod folder angesehen. Sollte eigentlich funktionieren. Kannst du mal die neueste [Version ](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.2.0) der Häcksel Mod laden, und - falls Problem weiter besteht - deine log.txt hier hochladen?

**Comment by Justice-Molton** [comment]
Hallo, 
vielen dank für die schnelle Rückmeldung, ich kann das gerne versuchen. Allerdings bin ich die nächsten 2 Wochen Beruflich unterwegs. Sobald ich wieder zuhause bin probiere ich es. Gestern ging es mit der neusten version nicht.
Es geht auf der Map an allen anderen Ballenverkäufen, ausser an der im Landhandel.

**Comment by sashaman** [comment]
da is kein chaff / choppedmaize eingetragen
```xml
    <sellingStation supportsExtension="false" litersForFullPriceDrop="100000" fullPriceRecoverHours="48" >
        <unloadTrigger exactFillRootNode="unloadTrigger" aiNode="aiNode" fillTypes="STRAW DRYGRASS_WINDROW GRASS_WINDROW SILAGE SUGARBEET_CUT ALFALFA_WINDROW DRYALFALFA_WINDROW CLOVER_WINDROW DRYCLOVER_WINDROW ALFALFA_FERMENTED CLOVER_FERMENTED" >
            <baleTrigger triggerNode="baleTrigger" deleteLitersPerSecond="10000"/>
        </unloadTrigger>
```

**Comment by Darkfaer666** [comment]
mahlzeit zusammen, hat sich hier was ergeben?? Ganzpflanze z.b. wird bei Kaliro [Strohandel), Tierhandel Ballen und Getreide Ag Ballen angenommen, aber **nicht** am Landhandel Ballen. habe mal versucht mit fillType einfügen, aber auch das ohne erfolg.
Version 1.0.3.0.
[log_2023-11-18_14-52-18.txt](https://github.com/Mmtrx/FS22_ChaffMission/files/13400651/log_2023-11-18_14-52-18.txt)

Nachtrag : Nach Liste der Aufträge löschen und neu generieren, wird der Landhandel für diese Missionen nicht mehr angefahren.

**Comment by Mmtrx** [comment]
..expired.
