### ISSUE TITLE
Nur so en Gedanke...

### ISSUE THREAD

**Issue by LSMT-elMatador** [Mmtrx/FS22_ChaffMission#16]
... die Häcksler-Missionen, welche Getreide (Weizen,Gerste, Hafer, Raps und Hirse) werden mit einem Maisgebiss geschnitten. Im realen aber eher mit einem Mähwerk (easyFlow, DirectDisc oder ähnliches).
Kann man das in der Mod eintragen, welches Schneidwerk vermietet wird?

**Comment by Mmtrx** [comment]
Moin,
kann ich in den nächsten update einbauen. Was ist mit Sonnenblumen häckseln, auch Mähwerk oder bleibt's da bei Maisgebiss?

**Comment by Justice-Molton** [comment]
Nur ein weiterer Gedanke, kann man auch die Jahrezeit anpassen. Mais wird zb nicht im August gehäckselt. GPS im allgemeinen auch früher als August.

**Comment by LSMT-elMatador** [comment]
Sonnenblumen/Mais/Silphie also alles was dicke Halme hat, das schafft ein normales Schneidwerk nicht... somit Maisgebiss
Weizen/ Gerste/ Hafer/ Raps/ Roggen/ Hirse  also alles was als "Getreide" geführt wird und nicht so dicke Halme hat. Da würde das Maisgebiss verstopfen. Ergo... Mähwerk
Auch die wahnsinnig hohen Erträge bei den Häckselaufgaben könnte man etwas runter schrauben. oder die Häufigkeit in der die Felder als Häckselgut-Felder in die Auftragsliste kommen. Sonst macht jeder nur noch Häckselaufträge. Da sich die Anderen Aufträge, im Verhältnis, nicht mehr rentieren! Sonst feiere ich die Mod absolut!

**Comment by Mmtrx** [comment]
Alles klar, danke fürs feedback!

Ertragskalkulation hab ich mich tatsächlich verhauen, wollte mich orientieren an Erntemissionen `(REWARD_PER_HA = 1500)`, hab aber die Konstante für Kartoffel-/ Rübenernte genommen `(REWARD_PER_HA = 4800)`. Habs jetzt geändert auf 2500.

Bei "häckselreifen" Feldern (Wachstumsstufe eine vor erntereif) wird jetzt nur noch in 50% der Fälle eine Mission erzeugt (genau wie bei erntereifen Feldern). 

@Justice-Molton, die mod guckt nur, ob ein Feld Wachstumsstufe "Futter" (meistens ist das erntereif - 1) oder Stufe "erntereif" erreicht hat. Wann das ist, legt der Wachstumskalender der jeweiligen Map fest.

Update sollte heute hier noch erscheinen: [1.0.3.0](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.3.0)

**Comment by Justice-Molton** [comment]
Das man bei Häckseln gut verdient ist aber auch nicht unrealistisch. Alleine der Aufwand an Maschinen rechtfertigt ein gutes income. Nur so als randnotiz.

**Comment by LSMT-elMatador** [comment]
Ich habe mir jetzt noch in den Grain Missionen die entsprechenden Schneidwerkswagen hinzugefügt!
Denn mit einem 4m und mehr Schneidwerk will man nicht über eine Karte fahren. Mit den Schneidwerkwagen geht es.
Bei dem Capello spartan610 Schneidwerk, habe ich den Krone xDisk620Trailer von Krone genommen. Funktioniert!

**Comment by rohne83** [comment]
> Alles klar, danke fürs feedback!
> 
> Ertragskalkulation hab ich mich tatsächlich verhauen, wollte mich orientieren an Erntemissionen `(REWARD_PER_HA = 1500)`, hab aber die Konstante für Kartoffel-/ Rübenernte genommen `(REWARD_PER_HA = 4800)`. Habs jetzt geändert auf 2500.
> 
> Bei "häckselreifen" Feldern (Wachstumsstufe eine vor erntereif) wird jetzt nur noch in 50% der Fälle eine Mission erzeugt (genau wie bei erntereifen Feldern).
> 
> @Justice-Molton, die mod guckt nur, ob ein Feld Wachstumsstufe "Futter" (meistens ist das erntereif - 1) oder Stufe "erntereif" erreicht hat. Wann das ist, legt der Wachstumskalender der jeweiligen Map fest.
> 
> Update sollte heute hier noch erscheinen: [1.0.3.0](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.3.0)

Wäre es nicht sinnvoller die Häckselaufträge halt einfach nur für Felder in der letzten Wachstumsstufe vor Erntereife zu generieren, dafür aber für wirklich alle Felder?
Zusammen mit betterContracts (vA davon den faulen Bauer) an, kann man damit für jedes Feld selbst entscheiden ob man häckselt oder drischt.
Mais wird ja zB hierzulande überwiegend gehäckselt und nur selten gedroschen, bei Getreide dagegen ist es genau umgekehrt. Wenn gehäckselt wird, dann aber fast immer wenn die Pflanze noch grün ist, und fast nie wenn sie schon gelb ist.

**Comment by Mmtrx** [comment]
Das Base Game lässt jeweils nur eine Mission pro Feld zu. Also kann man nur entweder eine Ernte- oder HäckselMission generieren lassen.

**Comment by rohne83** [comment]
Das ist mir bewusst, und ist ja auch gut so. Sehe daran auch kein Problem, denn für erntereife Felder sollte in meinen Augen generell kein Häckselauftrag mehr generiert werden, sondern nur noch normale Ernteaufträge (und auch diese dann wiederum für alle Felder). Häckselaufträge nur in der letzten Wachstumsstufe davor (ist ja eigentlich bei allen Früchten die Wachstumsstufe ab der gehäckselt werden kann, teilweise gehts glaub schon ein/zwei Monate früher).
Wenn man Häckseln will nimmt man sie da an, ansonsten wenn man lieber normal ernten will, lässt man die Häckselaufträge bei Monatswechsel durch Ernteaufträge ersetzen. Also quasi das selbe Prinzip wie bei der Unkrautbekämpfung (erst kommen Aufträge für mechanisch, und wenn die nicht gemacht werden, wird im Folgemonat stattdessen ein Spritzauftrag generiert).

Falls nötig auch ein Setting denkbar, a) so wie bisher, also eher Zufall ob Häcksel- oder Ernteauftrag generiert wird, b) Häckselaufträge für alle Felder, diese verfallen bei Erreichen der Erntereife aber so dass für die entsprechenden Felder wieder normale Ernteaufträge generiert werden können

**Comment by LSMT-elMatador** [comment]
Du verstehst offensichtlich die Base game Vorgaben nicht so richtig!
Also so:
Setting A: Häckselauftrag wird generiert: Egal in welcher Wachstums-Stufe. Wenn dieser dann nicht angenommen wird, KANN KEIN Ernteauftrag in der letzten Stufe mehr erstellt werden, da das Feld schon einen Auftrag generiert hat!
Setting B: Wenn kein Häckselauftrag erstellt wurde: Nur dann kann ein Ernteauftrag erstellt werden!

**Comment by rohne83** [comment]
Wie läuft das denn dann eigentlich bei den Unkrautaufträgen? Da funktionierts ja vom basegame her schon exakt genau so wie mir das auch für Häckseln vorgeschwebt ist: wenn man bis zum Monatswechsel den Auftrag für mechanische Beseitigung nicht angenommen hat, wird dieser gecancelt und dafür durch einen Spritzauftrag fürs selbe Feld ersetzt. Auf die Art hat man zusammen mit betterContracts die Möglichkeit für praktisch jedes Feld Spritzaufträge zu bekommen obwohl da ja vorher immer erst einer für Striegeln generiert wird.

Wenn sich das fürs Häckseln partout nicht nachahmen lässt, wäre es dann vielleicht möglich, die Wahrscheinlichkeit ob überhaupt Häckselaufträge generiert werden, fruchtartabhängig zu machen (falls das das Menü überladen würde, auch als xml-configfile denkbar)? Manche mögen ja darauf stehen, wenn sie auch Getreide oder gar Sonnenblumen häckseln können, aber mir ists schon wichtig dass ich alle Früchte außer eben Mais dreschen kann. Nur der Mais soll auch bei Aufträgen hauptsächlich gehäckselt werden ;)

**Comment by LSMT-elMatador** [comment]
Das liegt an dem Setting der Feldfrüchte! 
Sieh Dir mal die Fruittype.xml der map an. Dort findest Du für jede Frucht das Ernteverhalten
minHarvestingGrowthState="7" maxHarvestingGrowthState="7" heist nur in der 7. Wachstumsstufe kann gedroschen werden
minForageGrowthState="5" heisst dann, logischerweise, das ab diesem Wachstumsstadium das Häckseln erlaubt ist!

Wie viele Aufträge erzeugt werden, kann man im Häckselaufträge Mod einstellen! 
Dazu sollt man sich aber mit xml und Lua ein wenig auskennen!

Ich kann es nicht. Aber aus rein logischer Sicht, kann es nur so sein!

**Comment by Mmtrx** [comment]
ihr habt beide recht. Im Prinzip kann man alles programmieren. Und ja, das Spiel kann angebotene Missionen auch von sich aus wieder canceln. Wenn die Voraussetzungen (Wachstum Stufe) nicht mehr gegeben sind.

Aber ab sofort kümmere ich mich natürlich hauptsächlich um eine FS25 Version von BetterContracts.   
😉
