### ISSUE TITLE
Häcksel Missionen mit Maize+ und Göweil Pack

### ISSUE THREAD

**Issue by Janikra** [Mmtrx/FS22_ChaffMission#18]
Ich wollte gerne den gehäckselten Frischmais aus dem Auftrag mit der Göweil Vario Master pressen lassen und dann abgeben, jedoch werden die Ballen verkauft anstatt sie an die Mission anzurechnen. Wenn ich den Mais lose beim Verkaufstrigger abkippe, passiert das gleiche. Ich habe dann hier eine neuere Version geladen und meine gesehen zu haben, dass es auch kurzzeitig ging. Leider aktuell nicht mehr. Im Anhang meine Log. Vielen Dank für die Hilfe im Vorraus
[log.txt](https://github.com/Mmtrx/FS22_ChaffMission/files/13326516/log.txt)

**Comment by LSMT-elMatador** [comment]
Bei 396 Mods im Ordner solltest Deinen Rechner auf ein Podest stellen un Ihn anbeten. 

Hut ab... für nen Rycen 5 mit 16 GB Arbeitsspeicher... reife Leistung
Ich empfehle folgende Lektüre:

[Modordnerorganisation.pdf](https://github.com/Mmtrx/FS22_ChaffMission/files/13326750/Modordnerorganisation.pdf)

Dies lesen und 1 zu 1 befolgen!

Dann könnte Dein Rechner auch wieder alles schaffen, was er schaffen soll!

**Comment by Janikra** [comment]
Er packt alles was er soll, sogar auf guter Framerate. Standard Maps 70 FPS, auf der Landersum nur 40-50 FPS. 
Das Problem hat sich durch einen Neustart des Savegames und erneuten dowmload der Mods von alleine gelöst. Trotzdem danke.
