### ISSUE TITLE
The old problem with the delivery points has returned.

### ISSUE THREAD

**Issue by Maestro-Ralf** [Mmtrx/FS22_ChaffMission#19]
Strangely, the old problem of the delivery point has returned, the mods have stopped working again, they refuse to accept the cut.I returned the anticipatory version when this problem was fixed, everything is fine with it.

**Comment by vitalii2011** [comment]
I confirm. In 1.0.3.0 it is required to deliver to points that do not accept "Forage".

**Comment by sashaman** [comment]
This is most probably due to placeables missing the fitting trigger. Decision is based upon an existing filltype entry in sellingstation afaik

**Comment by Mmtrx** [comment]
Can that still be reproduced? Have you tried to delete all contracts (X) and generate new ones ingame?

**Comment by vitalii2011** [comment]
It's not the season for such contracts on my map right now.
If I'm not mistaken, the "impossible" delivery was in https://forbidden-mods.de/filebase/file/37473-fbm22-gaby-s-futterschuppen/

**Comment by vitalii2011** [comment]
No. I couldn't reproduce this problem. Perhaps now, for some unknown reason (the mod version is still the same - 1.0.3.0) - everything is fine.

**Comment by vitalii2011** [comment]
To avoid creating a new topic:
It seems that crops were displayed for Sowing contracts before?
![fsScreen_2024_08_19_13_03_31](https://github.com/user-attachments/assets/94f3fc69-d466-4b49-922b-3beb5e53550c)

**Comment by Mmtrx** [comment]
No, has not been implemented yet.
