### ISSUE TITLE
Häckselgut kann nicht abgeliefert werden

### ISSUE THREAD

**Issue by tomy852** [Mmtrx/FS22_ChaffMission#2]
Hallo, finde den Mod sehr cool. 
Nur leider hab ich ein Problem mit dem abliefern von dem Häckselgut, ich müsste es am Supermarkt Liefern aber das geht nicht.
Könnte es daran liegen das der Filltype Mais ist? und nicht das "vanilla" Häckselgut wegen dem MaisPlus Mod?
   
Grüsse
tomy852 
 
[log.txt](https://github.com/Mmtrx/FS22_ChaffMission/files/12806784/log.txt)
![fsScreen_2023_10_04_20_02_11](https://github.com/Mmtrx/FS22_ChaffMission/assets/51209411/e042555d-e43b-4b45-a9af-7c36a1cf92e3)
![fsScreen_2023_10_04_20_02_59](https://github.com/Mmtrx/FS22_ChaffMission/assets/51209411/657b7054-b6d3-410f-a843-a80f8604d964)

**Comment by Gordon-Dry** [comment]
maizePlus hat ja selbst das Skript
`scr\baleMissionGrassFermented.lua`
welches in den ersten 3 Zeilen die aussagt als Kommentar:
```
-- This replaces FillType.SILAGE with FillType.GRASS_FERMENTED within the active missions on each sellingStation as soon as addFillLevelFromTool is called, meaning as soon as something is trying to sell.
-- While not the most elegant this seems the easiest to make Silage missions work. Also there is no reason why a bale shouldn't be GRASS_FERMENTED with MaizePlus installed in an active grass mission so.. this shouldn't cause any issues.
-- Reworked by Braeven (Farming Agency) 02.01.2023 - Fixed displaying issue, that made silage missions look like hay missions
```
Ich weiß nicht, ob es eine globale Variable oder Boolean Wert gibt, auf den man prüfen kann, so dass eine andere Mod "weiß", dass maizePlus installiert ist, aber wenn ja, dann könnte es ähnlich gelöst werden.

Es scheint, dass es kein Github für maizePlus gibt, auf das man verlinken kann - also hier ist das oben erwähnte Skript als Referenz:
```
baleMissionGrassFermented = {}

function baleMissionGrassFermented.addFillLevelFromTool(self, superFunc, farmId, deltaFillLevel, fillType, fillInfo, toolType, extraAttributes)

	-- cycle through all missions attached to sellingStation and change fillType SILAGE to GRASS_FERMENTED
	for _, mission in pairs(self.missions) do
		if mission.fillType == FillType.SILAGE then
			mission.fillType = Utils.getNoNil(FillType.GRASS_FERMENTED, mission.fillType)		
		end
	end	
	
	-- call original func 
	return superFunc(self, farmId, deltaFillLevel, fillType, fillInfo, toolType, extraAttributes)
end
SellingStation.addFillLevelFromTool = Utils.overwrittenFunction(SellingStation.addFillLevelFromTool, baleMissionGrassFermented.addFillLevelFromTool)


function baleMissionGrassFermented:getData()
	if self.sellPointId ~= nil then
		self:tryToResolveSellPoint()
	end

	local l10nString = nil

	if self.fillType == FillType.SILAGE or self.fillType == FillType.GRASS_FERMENTED then
		l10nString = "fieldJob_desc_baling_silage"
	else
		l10nString = "fieldJob_desc_baling_hay"
	end

	return {
		location = string.format(g_i18n:getText("fieldJob_number"), self.field.fieldId),
		jobType = g_i18n:getText("fieldJob_jobType_baling"),
		action = g_i18n:getText("fieldJob_desc_action_baling"),
		description = string.format(g_i18n:getText(l10nString), self.field.fieldId, self.sellPoint:getName())
	}
end

BaleMission.getData = Utils.overwrittenFunction(BaleMission.getData, baleMissionGrassFermented.getData)
```

**Comment by Mmtrx** [comment]
Ja stimmt, Maize+ Kompatibilität ist noch nicht berücksichtigt. Tom liefert ja auch kein Std Häckselgut (CHAFF), sondern Frischmais 😉.
Ich werd mal sehen, wie ich das berücksichtigen kann.

**Comment by tomy852** [comment]
das wäre wirklich der Hammer, wenn sich da eine Lösung finden würde 😊

**Comment by braeven** [comment]
Der Grundsätzliche Code zum Überprüfen ist schon im Script drin für BetterContracts.
Es müsste nur FillType.Chaff zu FillType.CHOPPEDMAIZE werden, wenn M+ vorhanden wäre

**Comment by Danny24121992** [comment]
Moin erstmal 1a mod ich glaube da haben alle von uns drauf gewartet weil Giants ja nicht sich drum kümmert deswegen erstmal Dankeschön. Es ist zb so wenn man Silage Mission macht mit maizeplus steht da am Anfang auch ganzpflanzensilage in der Mission. Gibt man einen ballen ab ändert sich die Mission in Grassilage. Aber bei mir ist auch dasselbe Problem das die Verkaufsstellen kein Frischmais nehmen.

**Comment by Danny24121992** [comment]
Moin erstmal riesiges Dankeschön für den Mod. Es müssten quasi die Verkaufsstellen Frischmais ready gemacht werden auf den ganzen Karten.

**Comment by Mmtrx** [comment]
Try [v1.0.1.0](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.1.0) - should work now.

**Comment by tomy852** [comment]
Es funktioniert :) danke für den Fix!
