### ISSUE TITLE
Hi, not sure if this is the right place to report, I'm having a serious problem with the forage contracts mod.

### ISSUE THREAD

**Issue by keredg** [Mmtrx/FS22_ChaffMission#21]
First of all a great mods, thanks. The problem is with Forage contracts, It will not allow the Ballyspring map to load past 85%. It took me a couple of hours to find the problem with the amount of mods I use by a process of elimination but at the end with absolutely no other mods selected but forage Contracts, the map will not load past 85%. A completely empty mod folder other than Forage contracts, no other maps either, I have never had any problems with other maps and I have tried to report to the map makers but their server is not accepting messages.  
I am not a programmer of any kind, its wizardry to me so I have no idea where to look for the reason. Its a great shame as this mod is perfect for the ballysprings map. Thanks again for the mods and I wish you all the best for the new year.

**Comment by sirbum69** [comment]
The issue is with Line 91. Says its trying to report a nil back and can not. If you have the console enabled when you start a map it will show you where it errors at next time so you dont wait for ever and you know where to look to correct the error.

**Comment by Mmtrx** [comment]
Ok, thanks for your analysis. Will Look into this soon.

**Comment by sirbum69** [comment]
I found the issue. Theee is a ) on the last “end” of that line but there was not Ann open bracket for me.  Soon as i deleted the close brracket it loaded just fine

**Comment by keredg** [comment]
That's great news, thank you, I will check GitHub for an update when I get
home,
Regards
Derek

**Comment by Mmtrx** [comment]
Don't know how that happened, The[ source code](https://github.com/Mmtrx/FS22_ChaffMission/blob/main/chaffMission.lua) here does not have a ) on line 91.

Assuming this can be closed now.
