### ISSUE TITLE
Häcksegutmenge zu wenig.

### ISSUE THREAD

**Issue by Autobosl** [Mmtrx/FS22_ChaffMission#22]
Hallo ich finde den Mod absolut genial, das fehlt schon lange im Basisspiel.
aber warum ist die Menge an erzeugten Häckselgut so wenig? ist das so gewollt? ich würde gerne die Menge so haben als wie wenn ich im Spiel ohne Auftrag häcksle.
Wo kann man das anpassen?

**Comment by Autobosl** [comment]
Ich habe es gerade nochmal mit dem Ertrag nach dem Kauf des Feldes getestet. ist genau so wenig.
hat also nichts mit dem mod zu tun.

**Comment by Mmtrx** [comment]
Ok 😎
