### ISSUE TITLE
Errors/issues with ChaffMission...

### ISSUE THREAD

**Issue by FirenzeIT** [Mmtrx/FS22_ChaffMission#23]
Hello @Mmtrx, i have several warnings and errors with ChaffMissions, it's possible to fix them?? (tried with first 3 defaults map).. Without this mod, not have any of this issues... You have a beta version or dev of this mod ???

`2024-01-15 23:54 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_ChaffMission/chaffMission.lua:192: bad argument #1 to 'find' (string expected, got nil)
2024-01-15 23:54 Error: Running LUA method 'mouseEvent'.
dataS/scripts/sounds/SoundManager.lua(1157) : bad argument #1 to 'pairs' (table expected, got nil)
2024-01-15 23:54 Warning (script): Unknown entity id 383238 for 'object' in method 'delete'.
2024-01-15 23:54 LUA call stack:
  dataS/scripts/sounds/SoundManager.lua (1065) : delete
  dataS/scripts/placeables/specializations/PlaceablePlacement.lua (167) : deleteSample
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/placeables/Placeable.lua (591) : raiseEvent
  dataS/scripts/construction/ConstructionBrushPlaceable.lua (411) : delete
  dataS/scripts/construction/ConstructionBrushPlaceable.lua (101) : unloadPlaceable
  dataS/scripts/gui/ConstructionScreen.lua (223) : deactivate
  dataS/scripts/gui/ConstructionScreen.lua (719) : setBrush
  dataS/scripts/gui/elements/SmoothListElement.lua (1245) : raiseCallback
  dataS/scripts/gui/elements/SmoothListElement.lua (1227) : notifyClick
  dataS/scripts/gui/elements/SmoothListElement.lua (1299) : onMouseUp
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/base/Gui.lua (666) : mouseEvent
  dataS/scripts/events.lua (26) : mouseEvent
2024-01-15 23:54 Warning (script): Unknown entity id 383294 for 'object' in method 'delete'.
2024-01-15 23:54 LUA call stack:
  dataS/scripts/placeables/specializations/PlaceableDynamicallyLoadedParts.lua (159) : delete
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/placeables/Placeable.lua (591) : raiseEvent
  dataS/scripts/construction/ConstructionBrushPlaceable.lua (411) : delete
  dataS/scripts/construction/ConstructionBrushPlaceable.lua (101) : unloadPlaceable
  dataS/scripts/gui/ConstructionScreen.lua (223) : deactivate
  dataS/scripts/gui/ConstructionScreen.lua (719) : setBrush
  dataS/scripts/gui/elements/SmoothListElement.lua (1245) : raiseCallback
  dataS/scripts/gui/elements/SmoothListElement.lua (1227) : notifyClick
  dataS/scripts/gui/elements/SmoothListElement.lua (1299) : onMouseUp
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/base/Gui.lua (666) : mouseEvent
  dataS/scripts/events.lua (26) : mouseEvent
2024-01-15 23:54 Error: Running LUA method 'mouseEvent'.
dataS/scripts/sounds/SoundManager.lua(1157) : bad argument #1 to 'pairs' (table expected, got nil)
2024-01-15 23:54 Warning (script): Unknown entity id 383238 for 'object' in method 'delete'.`

[log.txt](https://github.com/Mmtrx/FS22_ChaffMission/files/13943607/log.txt)

**Comment by Mmtrx** [comment]
Hi,
the current dev [version ](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.3.0)is here.

And, from your log I see warnings from FS22_MultiFruitHarvesterPack (I think) that FS22_Contracts_Plus has no variants in its missionVehicles.xml. That could be a reason for your other [problem ](https://github.com/Mmtrx/FS22_BetterContracts/issues/190) with the missing vehicles for lime and chaff contracts.
Why do you need Contracts_Plus? Its functions are also in BetterContracts.

**Comment by FirenzeIT** [comment]
> Hi, the current dev [version ](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.3.0)is here.
> 
> And, from your log I see warnings from FS22_MultiFruitHarvesterPack (I think) that FS22_Contracts_Plus has no variants in its missionVehicles.xml. That could be a reason for your other [problem ](https://github.com/Mmtrx/FS22_BetterContracts/issues/190) with the missing vehicles for lime and chaff contracts. Why do you need Contracts_Plus? Its functions are also in BetterContracts.

Ok, i tried dev version of chaffmission and removed Contract_Plus, but now have another many issues, about (probably) DynamicMissionVehicles (multifruit harvester it's mandatory for this mod works). 

2024-01-17 06:15 Error: Running LUA method 'update'.
C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_DynamicMissionVehicles/src/DynamicMissionVehicles.lua:202: attempt to call field 'Warning' (a nil value)
2024-01-17 06:15 Error: Running LUA method 'update'.
scripts/missions/MissionManagerExtension.lua(180) : bad argument #1 to 'ipairs' (table expected, got nil)
2024-01-17 06:15 dataS/character/humans/npc/pedestrians/generic/npcCommon04_m.i3d (4.75 ms)
2024-01-17 06:15 dataS/character/player01/clothes/bottoms/botJeans.i3d (2.67 ms)
2024-01-17 06:15 Error: Running LUA method 'update'.
scripts/missions/MissionManagerExtension.lua(180) : bad argument #1 to 'ipairs' (table expected, got nil)
2024-01-17 06:15 Error: Running LUA method 'update'.
scripts/missions/MissionManagerExtension.lua(180) : bad argument #1 to 'ipairs' (table expected, got nil)
2024-01-17 06:15 Error: Running LUA method 'update'.
scripts/missions/MissionManagerExtension.lua(180) : bad argument #1 to 'ipairs' (table expected, got nil)

I don't know the way for find this lua inside all mods...

[log.txt](https://github.com/Mmtrx/FS22_ChaffMission/files/13958923/log.txt)

EDIT: I tried DynamicMissionVehicles (new update) and, without this, i don't have any issues (see log#2 below).  So the problems it's occured from **DynamicMissionVehicles**

[log#2.txt](https://github.com/Mmtrx/FS22_ChaffMission/files/13959136/log.2.txt)

**Comment by Mmtrx** [comment]
Ok, then I can close to this.
