### ISSUE TITLE
When I accept a forage contract it disappears if I borrow equipment

### ISSUE THREAD

**Issue by coatsy35** [Mmtrx/FS22_ChaffMission#25]
Is there known issues with forage contracts? everytime i see one and select one and borrow equipment it disappears from the list and no kit is borrowed - if I don't borrow kit, it's keeps it on my list and it works fine. I have the dynamic mission vehicles mod installed plus better contracts. Could this be it? Not sure what to log as nothing happens other than it vanishing from the list.

**Comment by Foss-ops** [comment]
Can confirm, same here. Better contracts version from Modhub, Chaff Mission from this github. Playing Local MP with my wife. 
Atleast the Github Version of Chaff mission works somewhat, the older modhub version breaks the ingame Job list. So it is usable if you bring your own equipment.

**Comment by coatsy35** [comment]
@Mmtrx are there any plans to fix this? it just doesn't work, even on a fresh install.

**Comment by Mmtrx** [comment]
Yes, I'm working on it. Problem is that I can't always reproduce the error - sometimes the contract with leased vehicles appears alright in the list as active. 

Could you upload a zipped savegame,save just before you accept the contract?

**Comment by Mmtrx** [comment]
I think DynamicMissionVehicles is not compatible with ChaffMission. If I activate both mods, I get following error in log file:
`Error: MissionType is not supported by DynamicMissionVehicles`

**Comment by coatsy35** [comment]
Fair enough. That’s a real shame as dynamic mission vehicles is a neat mod. I’ve uninstalled it and just using your ModHub versions of better contracts, chaff and lime and it all works atm.
