### ISSUE TITLE
Multiplayer errors

### ISSUE THREAD

**Issue by westor7** [Mmtrx/FS22_ChaffMission#26]
Hello,

I tried to place the mod in a rent server but when i open the contracts its messing up and giving errors.

[log.txt](https://github.com/Mmtrx/FS22_ChaffMission/files/15001676/log.txt)

- Thanks!

**Comment by Mmtrx** [comment]
I think that's an old bug. Please download latest version from [here](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.3.0)

**Comment by westor7** [comment]
Ah there 1.0.3 released ok , i've used the Modhub 1.0.0 version, are you willing to update on modhub too? because i use dedicate server.

- Thanks!

**Comment by Mmtrx** [comment]
ModHub version 1.0.4.0 has been released.
