### ISSUE TITLE
Häckselmission wenn Feld noch im Wachstum

### ISSUE THREAD

**Issue by MrDeadPool86** [Mmtrx/FS22_ChaffMission#27]
Hey wir haben im Multiplayer ein "Problem" undzwar werden Häcksel aufträge angeboten, obwohl das Feld noch im "Wachstum" ist. Könntest du das beheben oder ist es beabsichtigt?

Wenn beabsichtigt würdest du mir verraten was ich ändern muss, damit genau das nicht mehr Passiert?

Grund: Wir können zwar die Aufträge annehmen aber nicht bearbeiten da wir die Felder nicht Ernten können.

**Comment by Mmtrx** [comment]
Im Prinzip: works-as-designed. Häckseln kann man ja bereits bei Wachstumsstufe "erntereif" - 1. Daher werden auch bei dieser Wachstumsstufe HäckselAufträge erzeugt, 
es gibt aber auch Häcksel Aufträge auf erntereifen Feldern.

und was heißt: Wir können die Felder nicht ernten? Kann man nicht mit dem Häcksler drüber fahren?

**Comment by Mmtrx** [comment]
..expired
