### ISSUE TITLE
MIssion verschwindet direkt nach Annahme

### ISSUE THREAD

**Issue by MisterMedion** [Mmtrx/FS22_ChaffMission#28]
Wenn ich eine Häcksel Mission annehme, verschwindet diese direkt aus der Liste. Sie wird weder oben bei den aktiven Missionen angezeigt noch unten in der Liste der verfügbaren Missionen. Habe gecheckt ob das Feld Erntereif ist (ist es) und trotzdem tritt dieses Problem auf. Am Anfang hat der Mod funktioniert. Ich verwende es in Kombination mit Better Contracts. Beide auf dem letzten Versionsstand von hier

**Comment by Mmtrx** [comment]
Ist'n bug. Sollte mit der nächsten modhub version 1.0.4.0 gelöst sein.

**Comment by Mmtrx** [comment]
ModHub update ist nun verfügbar.
