### ISSUE TITLE
LUA Fehler auf der FS22_Oberthal

### ISSUE THREAD

**Issue by regs1980** [Mmtrx/FS22_ChaffMission#3]
Dein Mod macht den LUA Fehler 

![2023-10-13 16_36_00-Greenshot](https://github.com/Mmtrx/FS22_ChaffMission/assets/13314443/86039652-29ec-4862-bdcf-fddbd037a5ce)

bei Start der Map

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=274423&title=fs2022

**Comment by braeven** [comment]
Die Oberthal verwendet bei dieser Map Verkaufsstellen mit FillTypeCategories, was von den Chaffmissions nicht berücksichtigt ist, dürfte auf weiteren Maps/Mods zu dieser Art Problem kommen, da keine FillTypes ausgelesen werden können.

**Comment by XSunFireX** [comment]
Das selbe Problem hat die Multimap 4x auch. Wäre schön wenn das gefixt würde.

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=250583&title=fs2022

**Comment by Maestro-Ralf** [comment]
Dies ist ein Problem und ich hatte, ich habe mit den modifizierten Verkaufsstellen berechnet, das Skript funktioniert nicht mehr, entfernen Sie diesen modifizierten Verkaufspunkt und dann wird das Skript funktionieren.im Allgemeinen ist dies entweder ein Skript oder ein Verkaufsargument.

**Comment by Mmtrx** [comment]
Try [v1.0.1.0](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.1.0) - should work now.

**Comment by Maestro-Ralf** [comment]
Yes, the script is now working.Thank you.

**Comment by XSunFireX** [comment]
Local funktionierts, aber wenn ich versuche auf Server damit zu Starten, bleib ich im Bildschirm hängen geht kurz "Start" und dann lande ich wieder im Ladescreen.

**Comment by Mmtrx** [comment]
Hab einen fehlenden Wert bei MP Sync ergänzt. MP Oberthal läuft im MP. Andere Maps bitte testen mit dieser [Version](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.1.1).

**Comment by XSunFireX** [comment]
Werde dich weiter auf dem laufenden halten. 
Werde die 1.0.1.1 nachher auf den Server Laden und Testen, bei mir hat sie auf der Multimap nicht geladen - Server (siehe vorherigen Beitrag)

**Comment by XSunFireX** [comment]
Wie es aussieht, funkioniert das Mod schonmal auf der Department Haut Bayleron, werde sie weiter testen nun auch auf der Multimap, werde dich auf dem laufenden halten @Mmtrx

**Comment by Mmtrx** [comment]
Ich mach hier mal zu. Wenn es auf Multimap oder anderswo Probleme gibt, macht einen neuen Issue auf.
