### ISSUE TITLE
chaffMission.lua:192

### ISSUE THREAD

**Issue by Maestro-Ralf** [Mmtrx/FS22_ChaffMission#4]
Hello, I noticed this error  /FS22_ChaffMission/chaffMission.lua:192: bad argument #1 to 'find' (string expected, got nil) it appears due to mod points of sale. If you remove the mod point of sale, the script starts working.I think not everyone will be satisfied with this, so we need to fix something.

**Comment by Mmtrx** [comment]
Hi,
that's the same bug as in #3. Fix will come here (gitHub) soon. Will close this as duplicate.
