### ISSUE TITLE
Häckselmissonen verschwinden nach ein paar Sekunden wieder

### ISSUE THREAD

**Issue by Dueesberch** [Mmtrx/FS22_ChaffMission#7]
Bei uns verschwinden die Häckselmission nach 3-4 Sekunden, nachdem man das Lohndienstleistungsmenü geöffnet hat. Haben es mit / zu unterschiedlichen Uhrzeiten probiert. Das hat aber keinen Einfluss. 
Die Log zeigt weder Warning, noch Fehler. Kalkmissionen bleiben dagen lange in der Liste verfügbar.

**Comment by Mmtrx** [comment]
Hm,
MP oder single player? Wie ist die Zeiteinstellung (Tage/ Monat), welche Map? Mit oder ohne BetterContracts?

**Comment by Dueesberch** [comment]
Moin,
erstmal:
- Multiplayer
- 2 Tage / Monat
- [The Valley The Old Farm](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=268727&title=fs2022)
- Mit BetterContracts
Das ist die Liste der Mods die wir verwenden:
[games_fs22.json](https://github.com/Mmtrx/FS22_ChaffMission/files/13060516/games_fs22.json)
Die Prefixe `fsl_*!` bitte nicht beachten. Das games_fs22.json ist eine DB Datei meines eigenen Tools, mit dem ich unsere Spiele und die Mods zu den Spielen organisiere (kann unterschiedliche Versionen halten), sowie an meine Mitspieler verteile (deren Modlisten werden automatisch angepasst wenn ich das bei mir änder).

Nun aber zu meiner Erkenntnis / Vermutung. Aktuell befindet sich unser Spielstand im 2 Okt. Die Felder Sonnenblumen / Mais sind in Wachstumsstufe 5/6 (Futter). Wenn wir jetzt bis 6 Uhr schlafen und dann die Verträge öffnen sind kurzzeitig Häckselaufträge zu sehen. Der Status ist aber schon auf Erntereif gewechselt. Meine Vermutung ist nun, dass die Aufträge kurz nach dem öffnen deupdated werden und dadurch Erntereif verschwindet. Andererseits hab ich in einem Kopiespielstand einen Häckselauftrag für Sonnenblumen erntereif stehen, der nicht sofort verschwindet.

Leider bin ich nie durch die LS22 "Code-Doku" durchgestiegen, um mir ein Bild zumachen ob es sich hier um unglückliche Läufe der Listenupdates handelt oder die NCP doch zu schnell sind.

Falls meine Vermutung falsch ist und die Erntereifen Aufträge auch länger bestehen sollten, kann ich gerne etwas tiefer testen.

**Comment by Mmtrx** [comment]
Deine Vermutung ist ziemlich richtig.
Mein Skript löscht (noch nicht angenommene) Häckselaufträge, wenn die Frucht erntereif wird. Weil sonst nicht genügend Erntemissionen erzeugt werden könnten. 

Falls ein Feld ohne Mission erntereif wird, kann mit 40% Wahrscheinlichkeit ein Häckselauftrag erzeugt werden, mit 60% ein normaler Ernteauftrag.
Ausschnitt aus ChaffMission.canRunOnField():
```
	if maxGrowthState == fruitDesc.minForageGrowthState then
		return true, FieldManager.FIELDSTATE_GROWING, maxGrowthState

	elseif maxHarvestState ~= nil and math.random() < 0.4 then -- leave some fields for harvest missions
		return true, FieldManager.FIELDSTATE_GROWING, maxHarvestState
	end
```
Bis dahin also works-as-designed. Habt ihr denn insgesamt zu wenig Häckselmissionen? Dann könnte man die 0.4 oben ggf erhöhen.

**Comment by Dueesberch** [comment]
So. Hab jetzt nochmal mit Easydev tools gespielt und alle Felder auf Mais Wachstum 5/6 gesetzt. Dann bekomme ich 20 Auftrage bei 93 Feldern. Passt also alles.
